{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "asyncapi-server-api.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  annotations:
    cert-manager.io/issuer: {{ .Values.ingress.issuerName }} # here we use the name of the issuer we created through this chart.
spec:
  tls: 
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.ingress.secretName }}
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "asyncapi-server-api.fullname" . }}
            port:
              number: {{ .Values.ports.http }}
{{- end }}
