apiVersion: v1
kind: Service
metadata:
  name: {{ include "asyncapi-server-api.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "asyncapi-server-api.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: http
  selector:
    {{- include "asyncapi-server-api.selectorLabels" . | nindent 4 }}
